[project]
name = "permit-bleeding-edge-mockup"
authors = ["Bleeding Edge Technologies"]
description = "Advanced digital asset permit tracking and management system"
telemetry = false
requirements = []
[contracts.permit-tracking]
path = "contracts/permit-tracking.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
